version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "Telebot"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-22wt2ll52mt1"
s3_prefix = "Telebot"
region = "eu-central-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
